name = "bidusauto-live"
main = "worker.js"
compatibility_date = "2026-03-15"

[assets]
directory = "."

[observability]
enabled = true

[[kv_namespaces]]
binding = "CONTENT"
id = "2079d3f496df4a4d862a9ad21678e4ff"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"
